### ISSUE TITLE
ZeligBayesian not available for R 3.0.2

### ISSUE THREAD

**Issue by rlevitin** [christophergandrud/Rep-Res-Book#35]
Hi Chris,

I am trying to reproduce the book, it definitely looks interesting. I've managed to get past a handful of errors, but I'm stuck with the ZeligBayesian package.

I'm getting the following error, and can't find ZeligBayesian anywhere

``` R
...
Quitting from lines 49-109 (./Children/FrontMatter/Packages.Rnw) 
Quitting from lines 43-48 (./Children/FrontMatter/Packages.Rnw) 
Error in FUN(c("animation", "apsrtable", "brew", "countrycode", "data.table",  : 
  there is no package called 'ZeligBayesian'


> install.packages("ZeligBayesian", repos = "http://cran.us.r-project.org")
Warning in install.packages :
  package ‘ZeligBayesian’ is not available (for R version 3.0.2)
Installing package into ‘/home/ron/.Rlibrary’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘ZeligBayesian’ is not available (for R version 3.0.2)
```

**Comment by rfarouni** [comment]
Hi,
When I run the code in page xvii in the book, namely

`install.packages("ZeligBayesian",
                  repos = "http://r.iq.harvard.edu/", type  = "source")``

I get the following error
```
Installing package into ‘/home/rick/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100 11018  100 11018    0     0  25024      0 --:--:-- --:--:-- --:--:-- 25040
* installing *source* package ‘ZeligBayesian’ ...
** R
** inst
** preparing package for lazy loading
Note: the specification for S3 class “family” in package ‘MatrixModels’ seems equivalent to one from package ‘lme4’: not turning on duplicate class definitions for this class.
Error : objects ‘describe’, ‘param’, ‘qi’ are not exported by 'namespace:Zelig'
ERROR: lazy loading failed for package ‘ZeligBayesian’
* removing ‘/home/rick/R/x86_64-pc-linux-gnu-library/3.2/ZeligBayesian’
Warning in install.packages :
  installation of package ‘ZeligBayesian’ had non-zero exit status
```

**Comment by rfarouni** [comment]
I managed to resolve the issue by downloading the Zelig and ZeligBayesian packages from http://r.iq.harvard.edu/ and running the following code
```{R}
install.packages("Zelig_4.2-2.tar.gz", repos = NULL, type="source")
install.packages("ZeligBayesian_0.1.tar.gz", repos = NULL, type="source")
```

**Comment by christophergandrud** [comment]
Thanks. I'm actually taking ZeligBayesian out of the next edition (https://github.com/christophergandrud/Rep-Res-Book/issues/57). The package maintainers keep changing the structure of the package (making analyses using it difficult to reproduce) and the book only relies on the package for one small example.

**Comment by DDHGITHUB** [comment]
Great, what part to delete in the make file code that depends on ZeligBayesian ? thx

**Comment by salstfort** [comment]
I'm running R version 3.2.5, I'm not able to get the ZeligBaysian package installed as well. I'm getting the follownig  error:

> install.packages("ZeligBayesian", repos = "http://r.iq.harvard.edu", type = "source")
Installing package into ‘C:/Users/Salnave/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://r.iq.harvard.edu/src/contrib/ZeligBayesian_0.1.tar.gz'
Content type 'application/x-gzip' length 11018 bytes (10 KB)
downloaded 10 KB

* installing *source* package 'ZeligBayesian' ...
** R
** inst
** preparing package for lazy loading
Error : objects 'describe', 'param', 'qi' are not exported by 'namespace:Zelig'
ERROR: lazy loading failed for package 'ZeligBayesian'
* removing 'C:/Users/Salnave/Documents/R/win-library/3.2/ZeligBayesian'

The downloaded source packages are in
        ‘C:\Users\Salnave\AppData\Local\Temp\RtmpmIA1Sz\downloaded_packages’
Warning messages:
1: running command '"C:/R/R-3.2.5/bin/x64/R" CMD INSTALL -l "C:\Users\Salnave\Documents\R\win-library\3.2" C:\Users\Salnave\AppData\Local\Temp\RtmpmIA1Sz/downloaded_packages/ZeligBayesian_0.1.tar.gz' had status 1 
2: In install.packages("ZeligBayesian", repos = "http://r.iq.harvard.edu",  :
  installation of package ‘ZeligBayesian’ had non-zero exit status
I tried the other option that worked for rfarouni, I'm still getting an error:
> install.packages("ZeligBayesian_0.1.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/Salnave/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning: invalid package 'ZeligBayesian_0.1.tar.gz'
Error: ERROR: no packages specified
Warning messages:
1: running command '"C:/R/R-3.2.5/bin/x64/R" CMD INSTALL -l "C:\Users\Salnave\Documents\R\win-library\3.2" "ZeligBayesian_0.1.tar.gz"' had status 1 
2: In install.packages("ZeligBayesian_0.1.tar.gz", repos = NULL, type = "source") :
  installation of package ‘ZeligBayesian_0.1.tar.gz’ had non-zero exit status

**Comment by christophergandrud** [comment]
Please see the Errata on this issue: https://christophergandrud.github.io/RepResR-RStudio/errata.htm and also Issue https://github.com/christophergandrud/Rep-Res-Book/issues/57.
