### ISSUE TITLE
! LaTeX Error: File `StyleTemp.tex' not found.

### ISSUE THREAD

**Issue by m-dev-** [christophergandrud/Rep-Res-Book#41]
Thank you for putting your book online.  I've tried compiling it on a Windows 8.1 PC but get the error message:

output file: Rep-Res-Parent.tex
Error: running 'texi2dvi' on 'Rep-Res-Parent.tex' failed
LaTeX errors:
! LaTeX Error: File `StyleTemp.tex' not found.

I have Rtools installed and Highlight too.  I've checked Path environment variables.  Rtools is first in System Environment Path variable: c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin; ...

I have Pandoc installed, properly I hope.  I ran its Windows installer and it's the only value in User Environment Path variable: C:\Users\Mark\AppData\Local\Pandoc\

That's where pandoc.exe is, but I guess Pandoc installation is the underlying issue if StyleTemp.tex is not being generated.  I can't see how to resolve it though, I thought it might be the installation for one user, but I can't follow the instructions (http://johnmacfarlane.net/pandoc/faqs.html) to use the cabal tool to update Haskell or make it available for all users. Should I need Haskell to complete Pandoc installation and compile the book?  Does it matter if it's installed for one user (with admin rights), or should I make it a Pandoc question on stackoverflow?

**Comment by Hjalt** [comment]
I had the very same issue and also had to append "Source/" to the beginning of the file path.

**Comment by TanyaMurphy** [comment]
I had the same problem, but the suggested solution did not work. This finally did:
```
<<ChildStylisticConventions, include=FALSE>>=
pandoc("./Children/FrontMatter/StylisticConventions.md"
             , format = "latex",  ext = "tex")
file.copy("./Children/FrontMatter/StylisticConventions.tex"
               , "./StyleTemp.tex")
@
```
I am working on a Windows 10 computer, RStudio version 0.99.473, R version x64 3.2.2, and the packages installed through your `doInstall` section. I am afraid I'm not very good with command line tools other than R and I've cobbled together a repertoire of system commands from R (for better or worse).

**Comment by christophergandrud** [comment]
Thanks for the insights on other systems.
