### ISSUE TITLE
RStudio hangs at the Ch5ZipDownload-chunk in chapter 6

### ISSUE THREAD

**Issue by stefanherzog** [christophergandrud/Rep-Res-Book#62]
First of all: Great book!

# The problem: RStudio hangs at the Ch5ZipDownload-chunk in chapter 6

When I try to knit the whole book, RStudio hangs at the `Ch5ZipDownload`-chunk
(see code below, not evaluated here).

```{r original, eval = FALSE}
# For simplicity, store the URL in an object called 'URL'
URL <- "http://bit.ly/1jXJgDh"

# Create a temporary file called 'temp' to put the zip file into.
temp <- tempfile()

# Download the compressed file into the temporary file.
download.file(URL, temp)

```

# The underlying problem

The problem seems to be a HTTP error 406.
I use the `curl_download` function from the `curl` package so

- that R does not hang, and
- that I get an informative error message.

```{r download_problem_bitly, error = TRUE}
temp <- tempfile()
curl::curl_download("http://bit.ly/1jXJgDh", temp)
unlink(temp)

```

It also happens when using the direct URL.

```{r download_problem_direct, error = TRUE}
temp <- tempfile()
curl::curl_download(
        "http://www.unified-democracy-scores.org/files/20110104/uds_summary.csv.gz", 
        temp)
unlink(temp)

```

# A solution?

I was trying to find a solution (other than downloading the data and load it locally).
How can we get around the HTTP error 406? Thanks!

**Comment by christophergandrud** [comment]
Thanks for reporting this issue @stefanherzog. It looks like the bit.ly link is broken. bit.ly seems to have changed how they shorten that URL. 

The best solution is just to use the original URL. 

I've updated the book and posted a notice on the Errata page:

http://christophergandrud.github.io/RepResR-RStudio/errata.htm

**Comment by stefanherzog** [comment]
Thanks for fixing this so quickly!

(Almost finished reading the book. I love it.)

**Comment by christophergandrud** [comment]
:+1:
