### ISSUE TITLE
Installing R and RStudio on Ubuntu 14.04 LTS (Trusty Tahr)

### ISSUE THREAD

**Issue by organiker127** [christophergandrud/Rep-Res-Book#66]
The method for installing R and RStudio as suggested on  pp. xix-xx in "Reproducible Research with R and RStudio" (2nd Ed.) failed on two laptops from different manufacturers. I recommend the following procedure instead:

Open the terminal and enter:

sudo apt-get update
sudo dpkg-reconfigure locales 

Go to https://cran.r-project.org/mirrors.html and choose the “closest” R repository to you.  Highlight and copy that web address, e.g., http://watson.nci.nih.gov/cran_mirror/ at the National Cancer Institute.

Open the software center, go to the top of the screen to “Edit” → “Software Sources”, click the “Other Software” tab, and click the “Add” button.  When the dialog screen appears, type in “deb” followed by a space.  Paste in your chosen R repository, then add the path you will use for installing R.  On my laptops the path was “bin/linux/ubuntu trusty/”.  Note the space between “ubuntu” and “trusty”.  Your dialog line should look something like:

deb http://watson.nci.nih.gov/cran_mirror/bin/linux/ubuntu trusty/
  
Cick the “Add Source” button.  Enter your password when prompted.  You will see the new source checked.  Also check the “Source Code” line.  Click the “Close” button.  Close the software center.

WARNING:  Be very careful entering these changes!  If you make a mistake here, you will get warning of a serious error and the software center will no longer work.  If that happens, your only recourse may be to re-install Ubuntu from disk.

In the terminal, enter the following commands and enter “y” as prompted:

sudo apt-get -f install
sudo apt-get install libcurl4-gnutls-dev
sudo apt-get install libxml2-dev
sudo apt-get install r-cran-xml
sudo apt-get install r-cran-rjava
sudo apt-get install libssl-dev
sudo apt-get install synaptic 

This procedure installs the latest version of R.

For RStudio, go to https://www.rstudio.com/products/rstudio/download/ , choose the 64 bit version for Ubuntu 12.04+ (assuming you have a 64 bit CPU), and then open with the Software Center.  Open the software center, click the install button, enter password if prompted, and click the authenticate button.

Type “rstudio” in the Terminal.  Hit enter.  When RStudio comes up, right click on its icon on the launcher bar, and choose “lock to launcher”.

In RStudio, go to File → New File → RScript to open the Source Code Pane.  In the pane enter the R packages you need, viz.:

install.packages(c("brew", "countrycode", "devtools", "doMC", "dplyr", "ggplot2", "googleVis", "knitr", "lattice", "MCMCpack", "repmis", "RCurl", "rmarkdown", "texreg", "tidyr", "WDI", "xtable"))

Highlight the lines of code and click the “Run” button.

Note:  You need the latest “lattice” and “doMC” packages to install “Zelig”.

Once package installation is complete, enter

install.packages("Zelig")

install.packages("ZeligBayesian", repos = "http://r.iq.harvard.edu/", type = "source")

Unhappily, the last package failed to install on the second laptop.

**Comment by christophergandrud** [comment]
Hi @organiker127. Thank you for this detailed set of suggestions! 

My thought in that section was actually not to give detailed R installation instructions, which are widely available on the internet (and can vary considerably between systems), but to raise some possible issues that might trip up a new user. When you say that you could not do something successfully above, could you give me a better indication of what the specific issue was. That way I can make a general suggestion for issues to look out for.

Regarding Zelig. They recently released a new architecture that appears to no longer require a separate install of ZeligBayesian. However, the normal.bayes model that is discussed in the book seems to be broken in this new architecture. Thanks for prompting me to look into this. I reported a bug over on the Zelig repo (https://github.com/IQSS/Zelig/issues/108). Hopefully they will sort it out soon and I can make the appropriate changes.

Thanks again!

**Comment by organiker127** [comment]
Dr. Gandrud,

Thank you for following up on my issue.  The framework your gave in the 
second edition of your book allowed me to install the latest version of 
R after about four months of effort.  That came after three years of 
trying to follow the instructions in the first edition of "Reproducible 
Research".  The second edition's instructions allowed only the 
installation of R 3.0.2 but did not allow the installation of the 
devtools, ggplot2, repmis, and tidyr packages in R.  By installing the 
most recent version I could finally install all the packages required to 
reproduce your book!  I cannot understand why ZeligBayesian failed to 
install on my other laptop.

V/r,

Nate Adams

**Comment by rintoug** [comment]
m the clipboard.

**Comment by rintoug** [comment]
test
