### ISSUE TITLE
UNABLE TO BUILD RSTUDIO ON FEDORA 23 -64 BITS

### ISSUE THREAD

**Issue by carongangoo** [christophergandrud/Rep-Res-Book#67]
Hi everybody !

First of all HAPPY NEW YEAR 2016 & all the best with FEDORA 24 !( hope it will soon be released ) I started 2016 by a new challenge : BUILD AND INSTALL RSTUDIO on FEDORA 23.

I downloaded rstudio-master and tried to build it from srouce and that's what I get :

" CMake Warning (dev) at /root/Qt5.4.0/5.4/gcc_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:224 (configure_file): configure_file called with unknown argument(s):

COPY_ONLY

Call Stack (most recent call first): src/cpp/desktop/CMakeLists.txt:234 (qt5_add_resources) This warning is for project developers. Use -Wno-dev to suppress it.

CMake Error at src/cpp/session/CMakeLists.txt:23 (message): Dictionaries not found (re-run install-dependencies script to install)

-- Configuring incomplete, errors occurred! See also "/root/Downloads/rstudio-master/CMakeFiles/CMakeOutput.log". See also "/root/Downloads/rstudio-master/CMakeFiles/CMakeError.log". [root@caron rstudio-master]# "

I tried to downgrade gcc ( koz I 've gotgcc 5.1.1. on Fedora 23 ) an even to install dependencies I I succeeded in installing boot libraries but I cannot install " dependencies-yum" with sudo dnf install.I also succeeded in installing R with " sudo dnf install R "

What must I do please ?

Thanking you in advance for your time

Caron

**Comment by christophergandrud** [comment]
Happy New Year to you too!

Hm, I think you will have much better luck posting this query over at RStudio: https://support.rstudio.com/hc/en-us/sections/200096803-Troubleshooting

**Comment by carongangoo** [comment]
Thank you very much for your advice , If whenever you come across a solution, you're most welcome.

Regards

Caron
