### ISSUE TITLE
package RJSONIO needed

### ISSUE THREAD

**Issue by edusantana** [christophergandrud/Rep-Res-Book#68]
Hi, I'm using OpenSuse 42.0,

For me the make file didn't work:

```bash
Rep-Res-ExampleProject1/Analysis/Data> make
R CMD BATCH Gather1.R
Makefile:24: recipe for target 'Gather1.Rout' failed
make: *** [Gather1.Rout] Error 1
```

I needed to install `RJSONIO`, required by `WDI` to make it work:

```r
install.packages("RJSONIO")
```

**Comment by christophergandrud** [comment]
Hm I wonder why it didn't install when you installed WDI. . .

Anyways, thanks for reporting this!
