### ISSUE TITLE
The meanning of `.Rnw`

### ISSUE THREAD

**Issue by edusantana** [christophergandrud/Rep-Res-Book#71]
```latex
LaTeX documents that include {\emph{knitr}} code chunks are generally called R
Sweave\index{R Sweave}\index{Sweave} files and have the file extension {\tt{.Rnw}}. 
This terminology is a little confusing.
```

I was curious about the meaning of `.Rnw`. When you presented the `.Rmd` and `.Rmarkdown` I understood the meaning. But what does `nw` means? I try to associate it with the word *new* without the 'e', but it probably isn't.

Knowing the meaning of `nw` may help us to understand the root of the confusing terminology.

**Comment by christophergandrud** [comment]
Thanks for the suggestion. `nw` refers to 'noweb' a tool that Sweave builds on. This is mentioned earlier, but you're right it could be clearer. Updated in 6dd9f7be3f142b3b245d735f4370fed69dda47de
