### ISSUE TITLE
why learn console commands to knit at the end of chapter 3

### ISSUE THREAD

**Issue by edusantana** [christophergandrud/Rep-Res-Book#72]
At the end of chapter 3, the was a section that teaches us the R commands to knit files. 

```latex
\subsection{\emph{knitr} \& R}

As {\emph{knitr}} is a regular R package, you can of course, knit documents in R (or using 
the console in RStudio). All of the {\emph{knitr}} syntax in your markup document is the 
same as before, but instead of clicking a {\tt{Compile PDF}} or {\tt{knit HTML}} button
use the {\tt{knit}} function.
```

I was wondering, is that a good place to have it? I understood what you presented, but *without saying why I need to learn this*, I was just thinking: *"well, I don't need to know this, I will just use the button interface to compile things"*. I have assumed that this is an *advanced feature* that I'm not going to use on a near future. Unless there is a reason to learn it at this point of reading, I suggest to move this section to an other place.

**Comment by christophergandrud** [comment]
Thanks for the suggestion.
