### ISSUE TITLE
Add or ignore the `.Rproj` file to version control?

### ISSUE THREAD

**Issue by edusantana** [christophergandrud/Rep-Res-Book#73]
When I was reading the chapter 4, and the `.Rproj` file was presented, it would be nice to know if we should add or ignore this file to the version control system.

```latex
\section{Setting Directories as RStudio Projects}

If you are using RStudio, you may want to organize your files as Projects\index{RStudio!Projects}.
\label{CreateRStudioProject} You can turn a normal directory into an RStudio Project by clicking
on \texttt{File} in the RStudio menu bar and selecting \texttt{New Project\ldots}. (...) You will 
also notice in the Create Project pop-up window that you can build new project directories 
and create a project from a directory already under version control\index{version control} 
(we'll do this at the end of Chapter \ref{Storing}). When you create a new project you will see
that RStudio has put a file with the extension \texttt{.Rproj} into the directory.
```

I know that you will only present the git at the end the next chapter, but, even there, the image may suggest that we need to add it:

![Ad image?](https://raw.githubusercontent.com/christophergandrud/Rep-Res-Book/229b9904a0bb4cb26ad3a037009fead643c946d3/Source/Children/Chapter5/images5/GitAdd.png)

I remember that you said that we would run some script to load the session... but I don't know it this project file should or not be added to the version control.

**Comment by christophergandrud** [comment]
If you want to collaborate on an R Project with someone via GitHub it can definitely be a good idea to add the .Rproj file. That way all collaborators can easily work with the same project settings.
