### ISSUE TITLE
ZeligBayesian fails to load; Zelig package version 5.1.1

### ISSUE THREAD

**Issue by rmsharp** [christophergandrud/Rep-Res-Book#77]
> packageVersion("Zelig")
[1] ‘5.1.1’
> library(devtools)
> install_github("zeligdev/ZeligBayesian")
Downloading GitHub repo zeligdev/ZeligBayesian@master
from URL https://api.github.com/repos/zeligdev/ZeligBayesian/zipball/master
Installing ZeligBayesian
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/gg/ssmlr42x38s615dt4xn0zfnr0000gn/T/RtmpiSjSXR/devtools37e5cd55a23/zeligdev-ZeligBayesian-ba80e52'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

* installing *source* package ‘ZeligBayesian’ ...
** R
** inst
** tests
** preparing package for lazy loading
Error : objects ‘describe’, ‘param’, ‘qi’ are not exported by 'namespace:Zelig'
ERROR: lazy loading failed for package ‘ZeligBayesian’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ZeligBayesian’
Installation failed: Command failed (1)

**Comment by christophergandrud** [comment]
Thanks for the comment. ZeligBayesian is no longer supported by the Zelig maintainers and so will not load. Related to https://github.com/christophergandrud/Rep-Res-Book/issues/66. Perils of reproducibility
