### ISSUE TITLE
Dropbox Link for FinRegulator Data

### ISSUE THREAD

**Issue by jeffweltman** [christophergandrud/Rep-Res-Book#78]
Do you have a new link for the FinRegulatorData introduced in Ch.5 and then referenced again in Ch.7? The link provided in Ch.5 is http://bit.ly/14aS5qq which redirects to a Dropbox 404.

Thank you!

**Comment by christophergandrud** [comment]
Hi @jeffweltman 

Thanks for catching this. Dropbox apparently changed their URL format. The new link is:

https://www.dropbox.com/s/130c5ol3o2jjmgk/public.fin.msm.model.csv?raw=1

So you could download it with the rio package:

```r
URL <- "https://www.dropbox.com/s/130c5ol3o2jjmgk/public.fin.msm.model.csv?raw=1"

FinRegulatorData <- rio::import(URL)
```

**Comment by jeffweltman** [comment]
That did the trick. Many thanks!
